### ISSUE TITLE
dilate is missing dimension

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#477]
A recent change introduced a bug:

```julia
using Images: dilate
A = zeros(3,3,3)
A[1,1,1] = 1
B = dilate(A)
```
>3x3x3 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  0.0
 1.0  1.0  0.0
 0.0  0.0  0.0

>[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

>[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

The expected behavior is to perform 3D dilation as I am not specifying any region.

**Comment by bjarthur** [comment]
can you isolate the change to a specific commit using `git bisect` ?

**Comment by juliohm** [comment]
@bjarthur I am not following the development recently, I just found the issue because my package that depends on `Images.jl` was not terminating.

**Comment by juliohm** [comment]
@timholy I think this is a serious issue that may introduce bugs in other packages. @bjarthur could you assign a label to this issue like `bug`?

**Comment by timholy** [comment]
For the record, the last time that code changed in a functional way is May 20, 2015. Hard to imagine it's a recent bug.

**Comment by juliohm** [comment]
That is interesting! I started working with 3D examples just recently, that
is why it didn't affect me earlier.

-Júlio

**Comment by timholy** [comment]
Try it with `A = zeros(3,3,2)`. I'll leave it as an exercise for the reader to figure out what that works.

**Comment by juliohm** [comment]
Thank you Tim, I appreciate your help as usual :blush:  I cannot fix it myself anytime soon, the following weeks are hectic, many things happening at the same time...

**Comment by timholy** [comment]
It's not clear it should be fixed (meaning it's a difficult decision). I'll give you a hint: it's Matlab's fault.

**Comment by juliohm** [comment]
It has to do with MATLAB? What exactly?

-Júlio

**Comment by timholy** [comment]
Try `@which dilate(A)` and I think you'll figure it out.

**Comment by juliohm** [comment]
@timholy it expects an `AbstractArray{T,N}` for both `zeros(3,3,3)` and `zeros(3,3,2)` here. I still don't get it.

**Comment by timholy** [comment]
Notice how the default `region` comes from `coords_spatial(A)`? Let's play with it:
```jl
julia> coords_spatial(zeros(3,3,2))
3-element Array{Int64,1}:
 1
 2
 3

julia> coords_spatial(zeros(3,3,3))   # Huh?
2-element Array{Int64,1}:
 1
 2

julia> coords_spatial(zeros(3,3,4))
3-element Array{Int64,1}:
 1
 2
 3
```
So take a peek at the implementation of `coords_spatial` and it quickly leads you to try:
```jl
julia> colordim(zeros(3,3,2))
0

julia> colordim(zeros(3,3,4))
0
```
but
```jl
julia> colordim(zeros(3,3,3))
3
```
Aha!

When Images was first created, similarity to Matlab seemed important. Matlab assumes that a 3d array, of size 3 in the last dimension, is really a 2d RGB image.

This behavior is so insane, maybe we should get rid of it. OTOH, people seem to use `raw` and `separate`, which suggests a more Matlab-esque processing strategy. So perhaps that would annoy folks.

**Comment by juliohm** [comment]
I don't deal with RGB representation that much in my research. Interpreting the 3rd dimension as RGB channels is any better in terms of developing efficient image processing algorithms? To me it is just an undesirable inconsistency in the package, but it may not be for other folks. My vote is to remove this weird MATLAB "feature" if there is still time.

**Comment by juliohm** [comment]
Is anyone against the removal of this convention? Does GitHub support polls? I will open an issue asking them to add this feature...

**Comment by rsrock** [comment]
Nuke it from orbit. It's the only way to be sure.

**Comment by timholy** [comment]
I'm in favor of getting rid of it, and no one has voiced concerns.

**Comment by juliohm** [comment]
I believe this is fixed in the next version of Images. Closing the issue.
